embeddings {
  tensor_name: "Variable_3:0"
  metadata_path: "/home/restor/partage/apogee-parades/AED_autoencoder/notebooks/projectorsV1.0/projector_Conso_CVAE_5couches-Temp-L1/df_labels.tsv"
  sprite {
    image_path: "/home/restor/partage/apogee-parades/AED_autoencoder/notebooks/projectorsV1.0/projector_Conso_CVAE_5couches-Temp-L1/sprite_4_classes.png"
    single_image_dim: 180
    single_image_dim: 180
  }
}
