embeddings {
  tensor_name: "Variable_2:0"
  metadata_path: "/home/restor/partage/apogee-parades/AED_autoencoder/notebooks/logs/projector_Conso_WeekDay_Temp_4couches/df_labels.tsv"
  sprite {
    image_path: "/home/restor/partage/apogee-parades/AED_autoencoder/notebooks/logs/projector_Conso_WeekDay_Temp_4couches/sprite_4_classes.png"
    single_image_dim: 180
    single_image_dim: 180
  }
}
